<?php

namespace Tests\Feature;

use Tests\TestCase;
use taskbee\Models\Plan;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ViewSubscriptionPlans extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->basicPlan = factory(Plan::class)->states('basic')->create();
        $this->advancedPlan = factory(Plan::class)->states('standard')->create();
        $this->proPlan = factory(Plan::class)->states('premium')->create();

    }

    /** @test */
    public function customers_can_view_available_subscription_plans()
    {
        $response = $this->get('/pricing');

        $response->assertStatus(200);
        $response->assertViewIs('pricing.index');

        $response->assertSee($this->basicPlan->name);
        $response->assertSee($this->basicPlan->members_limit);
        $response->assertSee($this->basicPlan->amountInEur);

        $response->assertSee($this->advancedPlan->name);
        $response->assertSee($this->advancedPlan->members_limit);
        $response->assertSee($this->advancedPlan->amountInEur);

        $response->assertSee($this->proPlan->name);
        $response->assertSee($this->proPlan->members_limit);
        $response->assertSee($this->proPlan->amountInEur);
    }
}
